require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.7

  NewCops: enable

  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'bin/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
